### ISSUE TITLE
Unspecified ReturnType. 

### ISSUE THREAD

**Issue by SimonElbrink** [leo-alcantara/JPA_assignement#1]
I would recommend you to specify the type of list you are expecting.

[jpa_assignement] src/main/java/se/lexicom/jpa_assignement/repository/IngredientDAOImpl.java (Lines 37-42)

```

    @Override
    @Transactional
    public Collection<Ingredient> findAll() {
        Query query = entityManager.createQuery("SELECT i FROM Ingredient i");
        return query.getResultList();
    }
```

[Open in IDE](https://api.codestream.com/c/YUioFpa6zg9olfw9/7uKCDuGNQWiPzKd9sSny8Q?marker=6148b04cc55b717047cf886b&ide=default&src=GitHub) · [Open on GitHub](https://github.com/leo-alcantara/jpa_assignement/blob/14c93731bf863eba3ef432ba8aea6f9ae2c8f0fe/src/main/java/se/lexicom/jpa_assignement/repository/IngredientDAOImpl.java#L37-L42)
[jpa_assignement] src/main/java/se/lexicom/jpa_assignement/repository/RecipeCategoryDAOImpl.java (Lines 39-44)

```

    @Override
    @Transactional
    public Collection<RecipeCategory> findAll() {
        Query query = entityManager.createQuery("SELECT rc FROM RecipeCategory rc");
        return query.getResultList();
    }
```

[Open in IDE](https://api.codestream.com/c/YUioFpa6zg9olfw9/7uKCDuGNQWiPzKd9sSny8Q?marker=6148b04cc55b717047cf886d&ide=default&src=GitHub) · [Open on GitHub](https://github.com/leo-alcantara/jpa_assignement/blob/8752bccbe079faceb15a2388799fc2669737ed41/src/main/java/se/lexicom/jpa_assignement/repository/RecipeCategoryDAOImpl.java#L39-L44)
[jpa_assignement] src/main/java/se/lexicom/jpa_assignement/repository/RecipeDAOImpl.java (Lines 39-43)

```

    @Override
    @Transactional
    public Collection<Recipe> findAll() {
        return entityManager.createQuery("SELECT r FROM Recipe r").getResultList();
    }
```

[Open in IDE](https://api.codestream.com/c/YUioFpa6zg9olfw9/7uKCDuGNQWiPzKd9sSny8Q?marker=6148b04cc55b717047cf886f&ide=default&src=GitHub) · [Open on GitHub](https://github.com/leo-alcantara/jpa_assignement/blob/5615875fb22e86afa55d5d5936d263a0c4e3bb89/src/main/java/se/lexicom/jpa_assignement/repository/RecipeDAOImpl.java#L39-L43)
[jpa_assignement] src/main/java/se/lexicom/jpa_assignement/repository/RecipeIngredientDAOImpl.java (Lines 33-36)

```

    @Override
    public Collection<RecipeIngredient> findAll() {
        return entityManager.createQuery("SELECT r FROM RecipeIngredient r").getResultList();
    }
```

[Open in IDE](https://api.codestream.com/c/YUioFpa6zg9olfw9/7uKCDuGNQWiPzKd9sSny8Q?marker=6148b04cc55b717047cf8871&ide=default&src=GitHub) · [Open on GitHub](https://github.com/leo-alcantara/jpa_assignement/blob/5615875fb22e86afa55d5d5936d263a0c4e3bb89/src/main/java/se/lexicom/jpa_assignement/repository/RecipeIngredientDAOImpl.java#L33-L36)
[jpa_assignement] src/main/java/se/lexicom/jpa_assignement/repository/RecipeInstructionDAOImpl.java (Lines 35-39)

```

    @Override
    @Transactional
    public Collection<RecipeInstruction> findAll() {
        return entityManager.createQuery("SELECT r FROM RecipeInstruction r").getResultList();
    }
```

[Open in IDE](https://api.codestream.com/c/YUioFpa6zg9olfw9/7uKCDuGNQWiPzKd9sSny8Q?marker=6148b04cc55b717047cf8873&ide=default&src=GitHub) · [Open on GitHub](https://github.com/leo-alcantara/jpa_assignement/blob/5615875fb22e86afa55d5d5936d263a0c4e3bb89/src/main/java/se/lexicom/jpa_assignement/repository/RecipeInstructionDAOImpl.java#L35-L39)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by leo-alcantara** [comment]
Ok! I will. Thank you!

**Comment by leo-alcantara** [comment]
Thanks. I tried to set as a set and then get a return set, but couldn't find the right way. I guess a list would work, right?

**Comment by leo-alcantara** [comment]
Done. I tidied up a few things too, like exceptions for null input, and fixing some warnings.
