### ISSUE TITLE
Bi-Directionals.

### ISSUE THREAD

**Issue by SimonElbrink** [leo-alcantara/JPA_assignement#2]
@leoalcantara: Hi.
When i was debugging you application this morning i found that the relationships are not set up correctly.

When you created the connection to the recipe from the recipe all look good. but the relationships are not updated in RecipeCategory and RecipeIngredient.

This problem is not a DAO problem. I Suggest you to solve this by writing tests for the Recipe model class.

I what you to create more specific test for you Recipe Dao and maybe add more Recipes that you can find from.

[jpa_assignement] src/test/java/se/lexicom/jpa_assignement/DAO/RecipeDAOImplTest.java (Lines 45-63)

```

 @BeforeEach
    void setUp() {
        ingredientsList = new HashSet<>();
        recipeCategories = new HashSet<>();
        ingredient = new Ingredient("Salt");
        recipes = new HashSet<>();
        recipeIngredient = new RecipeIngredient(ingredient, 10, Measurement.GRAM, testRecipe);
        recipeCategory = new RecipeCategory("BBQ", recipes);
        recipeCategory2 = new RecipeCategory("Meat", recipes);
        ingredientsList.add(recipeIngredient);
        recipeCategories.add(recipeCategory);
        recipeCategories.add(recipeCategory2);
        categoryNames = new HashSet<>();
        categoryNames.add("BBQ");
        categoryNames.add("Vegan");

        testRecipe = testEntityManager.persist(new Recipe("Feijoada", ingredientsList, recipeInstruction, recipeCategories));
        testId = testRecipe.getRecipeId();
    }
```

[Open in IDE](https://api.codestream.com/c/YUioFpa6zg9olfw9/vvRo-dlZQgitpvqxA7SXtw?marker=6149cadb55ea4415ee826732&ide=default&src=GitHub) · [Open on GitHub](https://github.com/leo-alcantara/jpa_assignement/blob/3dae65a237569c661f522ebf08638f829b7ff016/src/test/java/se/lexicom/jpa_assignement/DAO/RecipeDAOImplTest.java#L45-L63)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by leo-alcantara** [comment]
Hey! Added some tests in RecipeDao, double checked the relationships including convenience methods in the model classes and did some tests on the recipe model class. Looks good, but I don't have your eyes and knowledge. Hopefully you can have a look at it tmw and we can discuss it. Thanks a lot. Good night!
